- name: Configure GitLab
  hosts: gitlab
  become: yes
  become_method: sudo
  vars_files:
    - encrypted_tokens.yml
    - encrypted_variables.yml
  vars:
    username: Test User
    user_login: testuser
    groupname: testgroup

  tasks:
  - name: Install gitlab-runner, python GitLab API wrapper and docker
    pacman:
      name:
        - gitlab-runner
        - docker
        - python-gitlab
      state: latest  

  - name: Create a group for SELinux project
    gitlab_group:
      api_url: https://gitlab.tqre.fi/
      api_token: "{{ token_api }}"
      name: "{{ groupname }}"
      validate_certs: no

  - name: Create a regular user for GitLab instance
    gitlab_user:
      api_url: https://gitlab.tqre.fi/
      api_token: "{{ token_api }}"
      validate_certs: no
      access_level: owner
      name: "{{ username }}"
      username: "{{ user_login }}"
      password: "{{ passwd_gitlab_user }}"
      group: "{{ groupname }}"
      email: email@example.com
      confirm: no

  - name: Create a directory for gitlab-runner's certificates
    file:
      path: /etc/gitlab-runner/certs
      state: directory

  - name: Put server certificate for runner to find
    copy:
      src: ../secrets/gitlab.crt
      dest: /etc/gitlab-runner/certs/gitlab.tqre.fi.crt

  - name: Register a shared runner
    gitlab_runner:
      api_url: https://gitlab.tqre.fi/
      api_token: "{{ token_api }}"
      description: Shared runner
      registration_token: "{{ token_runner }}"
      validate_certs: no

  - name: Start gitlab-runner
    service:
      name: gitlab-runner
      enabled: yes
      state: started

  - name: Import selinux project repository from GitHub
    gitlab_project:
      api_url: https://gitlab.tqre.fi/
      api_token: "{{ token_api }}"
      name: selinux
      group: "{{ groupname }}"
      import_url: https://github.com/tqre/selinux
      validate_certs: no
