- name: Configure GitLab
  hosts: gitlab
  become: yes
  become_method: sudo

  tasks:
  - name: Install gitlab-runner, python GitLab API wrapper and docker
    pacman:
      name:
        - gitlab-runner
        - docker
        - python-gitlab
      state: latest  

  - name: Create a regular user for GitLab instance
    gitlab_user:
      api_url: https://gitlab.tqre.fi/
      api_token: {{ api_token }}
      validate_certs: no
      access_level: guest
      name: Test
      username: test
      password: test
      email: test@test.test
      confirm: no

  - name: Create a directory for gitlab-runner's certificates
    file:
      path: /etc/gitlab-runner/certs
      state: directory

  - name: Put server certificate for runner to find
    copy:
      src: ../secrets/gitlab.crt
      dest: /etc/gitlab-runner/certs/gitlab.tqre.fi.crt
      
