- name: Set up a local gitlab-runner
  hosts: gitlab
  become: yes
  become_method: sudo

  tasks:
  - name: Install gitlab-runner and docker
    pacman:
      name:
        - gitlab-runner
        - docker
      state: latest  

  - name: Put admin user to docker group
    user:
      name: tqre
      groups: docker

  - name: Create a directory for gitlab-runner's certificates
    file:
      path: /etc/gitlab-runner/certs
      state: directory

  - name: Put server certificate for runner to find
    copy:
      src: ../secrets/gitlab.crt
      dest: /etc/gitlab-runner/certs/gitlab.tqre.fi.crt
      
