- name: Install a native GitLab instance
  hosts: gitlab
  become: yes
  become_method: sudo
  vars:
    - dbadminpasswd: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63633233323766653963303932653266613164313666333339666631353630373263396138353638
          6362306630633237346165323038633961313734356133380a313866346437666463616464656639
          63393638666230323163666265653938346337613666303562323564323361326261363666633535
          3638633364306633350a393663636533316265376165393364613134353136626638666665373637
          63396237616137393336316361653033653235626562326265643361316564306634666161313431
          3765373434646638633066313434333263336231643662306562
  vars_files:
    - encrypted_variables.yml

  tasks:
  - name: Install all needed packages
    pacman:
      name: 
        - postgresql
        - python-psycopg2
        - redis
        - nginx-mainline
        - gitlab
      state: latest

  - name: Initialize postgresql database cluster 
    command: initdb -D /var/lib/postgres/data -E UTF8
    become_method: sudo
    become_user: postgres
    args:
      creates: /var/lib/postgres/data/PG_VERSION

  - name: Start and enable postgresql database service
    service:
      name: postgresql
      enabled: yes
      state: started

  - name: Create gitlab database user
    postgresql_user:
      name: admin
      password: "{{ dbadminpasswd }}"
      role_attr_flags: SUPERUSER

  - name: Create gitlab database
    postgresql_db:
      name: gitlabhq_production
      owner: admin

  - name: Upload skeleton /etc/webapps/gitlab/database.yml configuration file
    copy:
      src: config_files/database.yml
      dest: /etc/webapps/gitlab/database.yml

  - name: Put database password into database.yml
    lineinfile:
      path: /etc/webapps/gitlab/database.yml
      regexp: "^  password: "
      line: "  password: {{ dbadminpasswd }}"

  - name: Upload redis configuration file
    copy:
      src: config_files/redis.conf
      dest: /etc/redis.conf

  - name: Start and enable redis cache database service
    service:
      name: redis
      enabled: yes
      state: started

  - name: Put gitlab user to redis group
    user: 
      name: gitlab
      groups: redis

  - name: Set /etc/webapps/gitlab/resque.yml configuration file
    copy:
      src: config_files/resque.yml
      dest: /etc/webapps/gitlab/resque.yml

  - name: Create file used for auth token generation - /etc/webapps/gitlab/secret
    lineinfile:
      path: /etc/webapps/gitlab/secret
      line: "{{ gitlab_secret }}"
      create: yes
      owner: root
      group: gitlab
      mode: 0640

  - name: Create file used for auth token generation - /etc/webapps/gitlab-shell/secret
    lineinfile:
      path: /etc/webapps/gitlab-shell/secret
      line: "{{ gitlab_shell_secret }}"
      create: yes
      owner: root
      group: gitlab
      mode: 0640

  - name: Fill in secret strings to /etc/webapps/gitlab/secrets.yml
    blockinfile:
      path: /etc/webapps/gitlab/secrets.yml
      create: yes
      owner: root
      group: gitlab
      mode: 0640
      block: |
        production:
          secret_key_base: {{ secret_key_base }}
          db_key_base: {{ db_key_base }}
          otp_key_base: {{ otp_key_base }}
          openid_connect_signing_key: {{ openid_connect_signing_key }}

  - name: Upload the main configuration file - /etc/webapps/gitlab/gitlab.yml
    copy:
      src: config_files/gitlab.yml
      dest: /etc/webapps/gitlab/gitlab.yml

  - name: Start the gitlab-gitaly service
    service:
      name: gitlab-gitaly
      enabled: yes
      state: started
 
  - name: Set correct permissions for /usr/share/webapps/gitlab/tmp
    file:
      path: /usr/share/webapps/gitlab/tmp
      state: directory
      owner: gitlab
      group: gitlab
      mode: 0755  

# Set up 'creates' - find out what files are missing before this command executes
  - name: Initialize the GitLab database
    become_method: sudo
    become_user: gitlab
    shell: env $(cat environment | xargs) bundle exec rake gitlab:setup force=yes
    args:
      chdir: /usr/share/webapps/gitlab

# set up webserver: nginx
