- name: Server configurations
  hosts: gitlab
  become: yes
  become_method: sudo
  vars_files:
    - encrypted_variables.yml

  tasks:
  - name: Enable testing repositories
    copy:
      src: config_files/pacman.testing
      dest: /etc/pacman.conf

  - name: Full system upgrade
    pacman:
      update_cache: yes
      upgrade: yes

  - name: Install packages - firewall
    pacman:
      name:
        - nftables
      state: latest

  - name: Upload firewall configuration file
    copy:
      src: config_files/nftables.conf
      dest: /etc/nftables.conf

  - name: Enable nftables firewall
    service:
      name: nftables
      enabled: yes
      state: started

  - name: Set up bashrc for user
    copy:
      src: config_files/bashrc
      dest: /home/tqre/.bashrc

  - name: Reboot the system
    reboot:
