- name: Full system update
  hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - encrypted_variables.yml

  tasks:
  - name: pacman -Suy
    pacman:
      update_cache: yes
      upgrade: yes
