- name: Test environment setup
  hosts: gitlab
  become: yes
  become_method: sudo
  vars_files:
    - encrypted_variables.yml

  tasks:
  - name: Install QEMU, arch-install-scripts and additional tools needed
    pacman:
      name:
        - qemu-headless
        - arch-install-scripts
        - parted
        - libvirt
        - virt-manager

  - name: Add gitlab-runner to libvirt group
    user:
      name: gitlab-runner
      groups: libvirt
      append: yes

  - name: Give gitlab-runner passwordless sudo access
    lineinfile:
      path: /etc/sudoers.d/gitlab-runner
      line: 'gitlab-runner ALL=(ALL) NOPASSWD: ALL'
      create: yes
      owner: root
      group: root
      mode: 0440

  - name: Start libvirt service daemon
    service:
      name: libvirtd
      enabled: yes
      state: started

  - name: Start virtlogd service
    service:
      name: virtlogd
      enabled: yes
      state: started

