- name: Install GitLab requisite programs
  hosts: gitlab
  become: yes
  become_method: sudo

  tasks:
  - name: Install postgresql database
    pacman:
      name: postgresql
      state: latest

  - name: Install redis server
    pacman:
      name: redis
      state: latest

  - name: Install nginx
    pacman:
      name: nginx-mainline
      state: latest

  - name: Initialize database cluster
    command: initdb -D /var/lib/postgres/data
    become_method: sudo
    become_user: postgres
    args:
      creates: /var/lib/postgres/data/PG_VERSION

# command: initdb -D /var/lib/postgres/data
# run as: postgres
# creates: use PG_VERSION -file

# start and enable the services:
# postgresql, redis, nginx

# configuration files
