- name: Install native GitLab on a fresh system
  hosts: gitlab
  become: yes
  become_method: sudo

  tasks:
  - name: Install postgresql database
    pacman:
      name: postgresql
      state: latest

  - name: Install redis server
    pacman:
      name: redis
      state: latest

  - name: Install nginx
    pacman:
      name: nginx-mainline
      state: latest

# command: initdb -D /var/lib/postgres/data
# run as: postgres
# creates: use PG_VERSION -file

# start and enable the services:
# postgresql, redis, nginx

# configuration files
