- name: Install GitLab
  hosts: gitlab
  become: yes
  become_method: sudo

  tasks:
  - name: Install all needed programs - postgresql, redis, nginx-mainline, gitlab
    pacman:
      name: 
        - postgresql
        - redis
        - nginx-mainline
        - gitlab
      state: latest

  - name: Initialize postgresql database cluster 
    command: initdb -D /var/lib/postgres/data
    become_method: sudo
    become_user: postgres
    args:
      creates: /var/lib/postgres/data/PG_VERSION

  - name: Start and enable postgresql database service
    service:
      name: postgresql
      enabled: yes
      state: started

  - name: Start and enable redis service
    service:
      name: redis
      enabled: yes
      state: started

# start and enable the services:
# postgresql, redis, nginx

# configuration files
