- name: Install a native GitLab instance
  hosts: gitlab
  become: yes
  become_method: sudo

  tasks:
  - name: Install all needed programs - postgresql, redis, nginx-mainline, gitlab
    pacman:
      name: 
        - postgresql
        - redis
        - nginx-mainline
        - gitlab
      state: latest

  - name: Initialize postgresql database cluster 
    command: initdb -D /var/lib/postgres/data
    become_method: sudo
    become_user: postgres
    args:
      creates: /var/lib/postgres/data/PG_VERSION

  - name: Start and enable postgresql database service
    service:
      name: postgresql
      enabled: yes
      state: started

# create gitlabhq_production db + user
# seed /etc/webapps/gitlab/database.yml with user+password

  - name: Start and enable redis cache database service
    service:
      name: redis
      enabled: yes
      state: started

# redis configuration to use sockets instead of TCP /etc/redis.conf
# add gitlab user to redis group
# then update /etc/webapps/gitlab/resque.yml to use sockets

# configuration file for gitlab: /etc/webapps/gitlab/gitlab.yml

# set up secrets: /etc/webapps/gitlab{,-shell}/secret
#                 /etc/webapps/gitlab/secrets.yml

# start gitlab-gitaly.service

# initialize GitLab db

# set up webserver: nginx
